name: Hexo CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Branch
      uses: actions/checkout@master

    - name: Install Node
      uses: actions/setup-node@master
      with:
        node-version: "v16.13.1"

    - name: Install
      run: |
        sudo npm install hexo-cli -g
        sudo npm install
        sudo pip install coscmd
        sudo pip install tccli

    - name: Config Env
      env:
        SECRET_ID: ${{ secrets.COS_API_ID }}
        SECRET_KEY: ${{ secrets.COS_API_KEY }}
        BUCKET: ${{ secrets.COS_BUCKET }} #改为自己的存储桶名称
        REGION: ap-shanghai #改为自己的地域
      run: |
        coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION
        tccli configure set secretId $SECRET_ID
        tccli configure set secretKey $SECRET_KEY
        tccli configure set region $REGION

    - name: Build
      run: |
        hexo clean
        hexo generate

    - name: Release
      run: |
        coscmd upload -rfs --delete ./public/ /
        tccli cdn PurgePathCache --cli-unfold-argument --Paths http://blog.itan90.cn/ --FlushType flush