name: Hexo CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Branch
      uses: actions/checkout@master

    - name: Install Node
      uses: actions/setup-node@master
      with:
        node-version: "v16.13.1"

    - name: Install
      run: |
        npm install hexo-cli -g
        npm install

    - name: Build
      run: |
        hexo clean
        hexo generate